sudo: required
services:
  - docker

before_install:
  - docker build -t willsputra/dckr-react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true willsputra/dckr-react-test npm test

after_success:
  - docker build -t willsputra/dckr-multi-client ./client
  - docker build -t willsputra/dckr-multi-nginx ./nginx
  - docker build -t willsputra/dckr-multi-server ./server
  - docker build -t willsputra/dckr-multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push willsputra/dckr-multi-client
  - docker push willsputra/dckr-multi-nginx
  - docker push willsputra/dckr-multi-server
  - docker push willsputra/dckr-multi-worker